import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { Providers } from "./providers";
import "./globals.css";

/** Tema + color primario antes del primer paint. */
const THEME_BOOTSTRAP = `
(function(){
  try {
    var t = localStorage.getItem('app_theme');
    var p = localStorage.getItem('app_primary_hex');
    document.documentElement.setAttribute('data-theme', (t === 'dark' || t === 'light') ? t : 'light');
    if (p && /^#[0-9A-Fa-f]{6}$/.test(p)) document.documentElement.style.setProperty('--primary-600', p);
  } catch (e) {}
})();
`;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      data-theme="light"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <Script
          id="theme-bootstrap"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP }}
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
